name: redux_dev_tools
description: Time Travel Dev Tools for Dart Redux
version: 0.5.2
homepage: https://github.com/brianegan/redux_dev_tools
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ^5.0.0

dev_dependencies:
  coverage: ^1.0.1
  test: ^1.16.8
