name: redux_dev_tools
description: Time Travel Dev Tools for Dart Redux
version: 0.7.0
homepage: https://github.com/brianegan/redux_dev_tools

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ">=5.0.0 <6.0.0"

dev_dependencies:
  pedantic: ">=1.11.0 <2.0.0"
  coverage: ">=1.0.1 <2.0.0"
  test: ">=1.16.8 <2.0.0"
